[theme]
# Hijau sebagai warna utama untuk widget interaktif
primaryColor = '#4CAF50'

# Latar belakang utama aplikasi (putih)
backgroundColor = '#FFFFFF'

# Latar belakang sidebar dan area sekunder (abu-abu terang)
secondaryBackgroundColor = '#F0F2F6'

# Biru Dongker untuk warna teks utama
textColor = '#003366'

# Menggunakan font 'serif' yang akan diterapkan sebagai Times New Roman
font = 'serif'
