[theme]
# Warna utama Kemenkeu DJPB
primaryColor = "#005FAC"  # Biru DJPB
backgroundColor = "#FFFFFF"  # Putih bersih
secondaryBackgroundColor = "#F0F5F9"  # Abu-abu biru muda
textColor = "#000000"  # Hitam pekat (untuk kontras maksimal)
font = "sans serif"  # Font profesional

# Opsional (tambahkan di bawah [theme] jika perlu)
base = "light"
